name: Manual trigerring of Snyk scan
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'     
        required: true
        default: 'master' 
        type: choice
        options:
        - develop
        - master 
jobs:
 build:
   runs-on: ubuntu-latest
   strategy:
      matrix:
        node-version: [12.x]
   steps:
     - uses: actions/checkout@v2
       with:
          ref: ${{ github.event.inputs.branch }}
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
         node-version: ${{ matrix.node-version }}
     - name: Snyk Test
       uses: snyk/actions/setup@master
     - run: snyk test --sarif-file-output=snyk-sarif.json
       continue-on-error: true       
       env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
     - run: |
         git status
         echo "${{ github.event.inputs.branch }}"
         aws help
